### ISSUE TITLE
tools over tag after mouse hover

### ISSUE THREAD

**Issue by FadeMind** [tentin-quarantino/wykop-the-best-style#12]
![20230119-1674148919](https://user-images.githubusercontent.com/9846948/213516008-9c906cad-b2eb-466e-b307-8452c4bcdded.png)

**Comment by tentin-quarantino** [comment]
https://user-images.githubusercontent.com/122933810/213558084-0481b985-c435-4834-bf7a-3d3581123cc6.mp4
