### ISSUE TITLE
Na Edge pod Linuksem nie uruchaia się, nei robi żadnej zmiany

### ISSUE THREAD

**Issue by WMP** [tentin-quarantino/wykop-the-best-style#19]
![image](https://user-images.githubusercontent.com/45381/214016955-641659f7-14be-46c7-8a27-ce7c61d77f29.png)

**Comment by tentin-quarantino** [comment]
Styl póki co jest tylko dla trybu nocnego

**Comment by tentin-quarantino** [comment]
Dopisałem o tym w readme
