### ISSUE TITLE
Zmniejszanie obrazków na mikroblogu

### ISSUE THREAD

**Issue by rjolina** [tentin-quarantino/wykop-the-best-style#26]
Proszę o dodanie funkcji umożliwiającej zmniejszanie obrazków na mikroblogu.

Próbowałem sobie sam to ogarnąć, ale aż taki biegły nie jestem xD
```
.entry-photo {
    transform: scale(0.5);
}

```
Obrazki się zmniejszają, ale pozostaje dookoła nich szeroka obwódka.

**Comment by tentin-quarantino** [comment]
Dodano
