### ISSUE TITLE
Uzupełnij swój profil 

### ISSUE THREAD

**Issue by FadeMind** [tentin-quarantino/wykop-the-best-style#8]
Na kontach bez wypełnionego kwestionariusza jest belka 
![20230119-1674138815](https://user-images.githubusercontent.com/9846948/213470243-f92c1607-deca-4937-b205-6c342197e3dd.png)
![20230119-1674138801](https://user-images.githubusercontent.com/9846948/213470250-f914a71a-4ff0-4cf6-8eb9-b5668f71b052.png)

**Comment by tentin-quarantino** [comment]
I co jest nie tak z tą belką?

**Comment by FadeMind** [comment]
Zielony domyślny kolor, Twój CSS go nie rusza.

**Comment by tentin-quarantino** [comment]
IMO jest ładny, masz propozycję innego koloru?

**Comment by FadeMind** [comment]
Wrzuciłem issue jako informację, bo może kiedyś pomieszają znowu ;) Jeżeli tobie pasuje obecny wygląd to nie ma co zawracać sobie tym głowę. Pozdrawiam

**Comment by tentin-quarantino** [comment]
To póki co zostanie. Dzięki za czujność i za pomoc, zamykam
