### ISSUE TITLE
Nazwa użytkownika po prawej

### ISSUE THREAD

**Issue by amacierzynski** [tentin-quarantino/wykop-the-best-style#9]
![image](https://user-images.githubusercontent.com/12518073/213471098-1cd61c95-4b66-41b5-aa16-f23dae363585.png)

Domyślnie pokazuje mi się po prawej. Dopiero na Hoover leci do lewej. 

Chrome Version 109.0.5414.75 (Official Build) (64-bit)
Używam Stylebot'a do stylowania

**Comment by tentin-quarantino** [comment]
Może to kwestia Stylebota, bo jeszcze żaden z użytkowników nie zgłosił mi takiego błedu. Możesz sprawdzić na najnowszej wersji stylu?

**Comment by amacierzynski** [comment]
Sprawdziłem ale niestety nie pomga. Próbowałem to sam znaleźć, ale szczerze wygląda wszystko ok. Spróbowałem na Stylebocie i tam wszystko jest git, więc może bug w tym moim. Także zamykam, bo szkoda utrzymywać 2 wersje.
